let shopItemData = 
[
    {
        id: "item1",
        name: "Grilled Salmon",
        price: 45,
        img: "images/item1.jpeg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item2",
        name: "Shrimp",
        price: 65,
        img: "images/item2.png",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item3",
        name: "Grilled Steak",
        price: 85,
        img: "images/item3.jpeg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item4",
        name: "Mashawy",
        price: 100,
        img: "images/item4.jpeg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item5",
        name: "Kofta Hati",
        price: 85,
        img: "images/item5.jpeg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item6",
        name: "Cheese Pizza",
        price: 65,
        img: "images/item6.jpeg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item7",
        name: "Pepperoni Pizza",
        price: 75,
        img: "images/item7.jpeg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item8",
        name: "chicken Pizza",
        price: 75,
        img: "images/item8.png",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item9",
        name: "Chicken Nuggets",
        price: 75,
        img: "images/item9.png",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item10",
        name: "Chicken Strips",
        price: 75,
        img: "images/item10.png",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item11",
        name: "Mesahab Chicken",
        price: 80,
        img: "images/item11.png",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
        id: "item12",
        name: "Onion Rings",
        price: 30,
        img: "images/item12.png",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
];
